//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDataGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleDataGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abel
        ///Abelardo
        ///Abílio
        ///Abraão
        ///Abrahão
        ///Abrão
        ///Ada
        ///Adalberto
        ///Adalgisa
        ///Adão
        ///Adela
        ///Adelaide
        ///Adelberto
        ///Adèle
        ///Adélia
        ///Adelina
        ///Ademar
        ///Adhemar
        ///Adolfo
        ///Adolpho
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianne
        ///Adriano
        ///Adriene
        ///Adrienne
        ///Afonso
        ///Ágata
        ///Agatha
        ///Agenor
        ///Agnaldo
        ///Agnes
        ///Agostinho
        ///Aguinaldo
        ///Aída
        ///Aiko
        ///Aílton
        ///Aimée
        ///Airton
        ///Ajit
        ///Akahana
        ///Akako
        ///Alaíde
        ///Alana
        ///Alane
        ///Alanna
        ///Alanne
        ///Alba
        ///Alberta
        ///Albertina
        ///Alberto
        ///Alceu
        ///Alcides
        ///Alcione
        ///Alcyone
        ///Alda
        ///Aldaberto
        ///Aldine
        ///Aldo
        ///Alec
        ///Alecsandra
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nomes {
            get {
                return ResourceManager.GetString("nomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  COSTABEBER CRESTANA CUNEGATO DA MEDA DAI ZOVI 
        ///DAL MOLIN DA MEDA DALLA POZZA DALLE ORE DOMASCHI DRAGO
        ///ABADI ABADIE ABAM ABARNO ABATE ABATI ABATTI ABBAD 
        ///ABBOTT ABBRUZZINO ABDALA ABDALLA ABDO ABECH ABEL 
        ///ABELE ABIBI ABRAHAO ABRANCHES ABRANTES ABRAO ABREU 
        ///ABRUZZI ABUD ABUJAMRA ACAUAN ACCHUTTI ACCURSO 
        /// 
        ///ABARNO ABATE ABATI ABATTI ABBAD ABBOTT ABBRUZZINO 
        ///ABDALA ABDO ABECH ABEL ABELE ABIBI ABRAHAO ABRANCHES 
        ///ABRANTES ABRAO ABREU ABRUZZI ABUD ABUJAMRA ACAUAN 
        ///ACCHUTTI ACCURSO ACEVEDO ACHE ACHILE ACHT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sobrenomes {
            get {
                return ResourceManager.GetString("sobrenomes", resourceCulture);
            }
        }
    }
}
